### ISSUE TITLE
Should `layer` be syntax highlighted?

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-css#24] opened 2023-11-29 20:45 UTC
```css
@import url('bootstrap/scss/bootstrap.scss') layer(bootstrap);
```
 _Originally posted by @TylerLeonhardt in [#180631](https://github.com/microsoft/vscode/issues/180631#issuecomment-1832672996)_

**Comment by andreamah** [comment] 2023-11-30 23:45
duplicate of https://github.com/microsoft/vscode-css/issues/17

**Closed by andreamah** 2023-11-30 23:45 UTC
